# Generated by Django 2.0.3 on 2020-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_details', '0001_initial'),
        ('customer', '0001_initial'),
        ('order', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentId', models.AutoField(auto_created=True, max_length=120, primary_key=True, serialize=False)),
                ('shipmentDate', models.DateTimeField(auto_now=True)),
                ('shipmentReference', models.CharField(blank=True, max_length=120)),
                ('billing_details', models.ForeignKey(on_delete=True, to='billing_details.Billing_details')),
                ('customer', models.ForeignKey(on_delete=True, to='customer.Customer')),
                ('shipmentItems', models.ManyToManyField(to='order.Order')),
                ('transport', models.ForeignKey(on_delete=True, to='transport.Transport')),
            ],
        ),
    ]
