# Generated by Django 2.0.3 on 2020-02-12 20:05

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_details', '0001_initial'),
        ('transport', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.BigIntegerField(blank=True, max_length=120)),
                ('shipmentDate', models.DateTimeField(auto_now=True)),
                ('shipmentReference', models.CharField(blank=True, max_length=120)),
                ('shipmentItems', django_mysql.models.ListCharField(models.IntegerField(), max_length=120, size=None)),
                ('billing_details', models.ForeignKey(on_delete=True, to='billing_details.Billing_details')),
                ('customer', models.ForeignKey(on_delete=True, to='customer.Customer')),
                ('transport', models.ForeignKey(on_delete=True, to='transport.Transport')),
            ],
        ),
    ]
