# Generated by Django 2.0.3 on 2020-02-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('shipment', '0002_auto_20200225_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipmentItems',
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipmentItems',
            field=models.ManyToManyField(to='order.Order'),
        ),
    ]
