# Generated by Django 2.0.3 on 2020-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(blank=True, max_length=120)),
                ('houseNumber', models.CharField(blank=True, max_length=120)),
                ('houseNumberExtended', models.CharField(blank=True, max_length=120)),
                ('addressSupplement', models.CharField(blank=True, max_length=120)),
                ('extraAddressInformation', models.CharField(blank=True, max_length=120)),
                ('zipCode', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('countryCode', models.IntegerField(blank=True)),
            ],
        ),
    ]
