# Generated by Django 2.0.3 on 2020-02-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('streetName', models.CharField(blank=True, max_length=120)),
                ('houseNumber', models.CharField(blank=True, max_length=120)),
                ('houseNumberExtended', models.CharField(blank=True, max_length=120)),
                ('addressSupplement', models.CharField(blank=True, max_length=120)),
                ('extraAddressInformation', models.CharField(blank=True, max_length=120)),
                ('zipCode', models.IntegerField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('countryCode', models.IntegerField(blank=True, max_length=4)),
            ],
        ),
    ]
