# Generated by Django 2.0.3 on 2020-02-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200212_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='countryCode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zipCode',
        ),
    ]
